from .instant_runoff_mechanism import InstantRunoffMechanism
from .median_mechanism import MedianMechanism
from .plurality_mechanism import PluralityMechanism
from .weighted_instant_runoff_mechanism import WeightedInstantRunoffMechanism
