from .borda_mechanism import BordaMechanism
from .closest_mechanism import ClosestMechanism
from .distance_mechanism import DistanceMechanism
from .equal_weight_mechanism import EqualWeightMechanism
from .weighting_mechanism import WeightingMechanism
